module.exports = {
  docsSidebar: [
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'getting-started/contrast-cli',
        {
          type: 'link',
          label: 'Contrast Platform',
          href: 'https://docs.contrastsecurity.com/en/get-started.html'
        }
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        {
          type: 'link',
          label: 'Use Contrast',
          href: 'https://docs.contrastsecurity.com/en/use-contrast.html'
        },
        {
          type: 'autogenerated',
          // label: 'Learn DevSec',
          dirName: 'guides'
        }
      ],
    },
    {
      type: 'link',
      label: 'Agents',
      href: 'https://docs.contrastsecurity.com/en/agents.html'
    },
    {
      type: 'link',
      label: 'Integrations',
      href: 'https://docs.contrastsecurity.com/en/integrations.html'
    },
    {
      type: 'link',
      label: 'Administration',
      href: 'https://docs.contrastsecurity.com/en/administration.html'
    },
    {
      type: 'link',
      label: 'Reference',
      href: 'https://docs.contrastsecurity.com/en/reference.html'
    },
    {
      type: 'link',
      label: 'REST API',
      href: 'https://api.contrastsecurity.com',
    },
    {
      type: 'link',
      label: 'Release News',
      href: 'https://docs.contrastsecurity.com/en/release.html'
    },
    // {
    //   type: 'category',
    //   label: 'Docusaurus',
    //   items: [
    //     {
    //       type: 'doc',
    //       id: 'doc2',
    //     },
    //     {
    //       type: 'doc',
    //       id: 'doc3',
    //     },
    //   ],
    // },
  ],
};